### ISSUE TITLE
Setting aoc_session_file in setup.cfg not detected

### ISSUE THREAD

**Issue by eruvanos** [j0057/pytest-aoc#1]
Due to the given default here
https://github.com/j0057/pytest-aoc/blob/24351ace572a76c75a77be761c57ccaf0b5d9c5f/pytest_aoc.py#L18

The option will always be `.cookie` unless it is overwritten with an empty value.
https://github.com/j0057/pytest-aoc/blob/24351ace572a76c75a77be761c57ccaf0b5d9c5f/pytest_aoc.py#L72

**Comment by j0057** [comment]
Hi Maic, thanks for raising the issue. I see it also happens on the `--aoc-input-dir` option.

I'll fix it and push a release to PyPI. (That second part is probably more work.) If I understand correctly, you do have a workaround, yes?

**Comment by j0057** [comment]
Thanks again, I've pushed version 1.20.0 here and PyPI.
